import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

/** Shared compat constant — avoids repeating the cast across ~30 model entries. */
export const NO_DEV_ROLE_COMPAT = {
    supportsDeveloperRole: false,
} as ProviderModelConfig["compat"];

// ── Static fallback models (CPA down) ──
export const STATIC_FALLBACK_MODELS: ProviderModelConfig[] = [
    // OpenCode Go (8)
    {
        id: "ocg/go-glm-5.2",
        name: "GLM 5.2 (Go)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-glm-5.1",
        name: "GLM 5.1 (Go)",
        reasoning: true,
        input: ["text"],
        contextWindow: 200_000,
        maxTokens: 128_000,
        cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-kimi-k2.7-code",
        name: "Kimi K2.7 Code (Go)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 262_144,
        maxTokens: 33_000,
        cost: { input: 0.95, output: 4.0, cacheRead: 0.19, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-kimi-k2.6",
        name: "Kimi K2.6 (Go)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 262_144,
        maxTokens: 16_384,
        cost: { input: 0.95, output: 4.0, cacheRead: 0.16, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-deepseek-v4-pro",
        name: "DeepSeek V4 Pro (Go)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 384_000,
        cost: { input: 1.74, output: 3.48, cacheRead: 0.0145, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-deepseek-v4-flash",
        name: "DeepSeek V4 Flash (Go)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 384_000,
        cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-mimo-v2.5",
        name: "MiMo V2.5 (Go)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 128_000,
        cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "ocg/go-mimo-v2.5-pro",
        name: "MiMo V2.5 Pro (Go)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 1_000_000,
        cost: { input: 1.74, output: 3.48, cacheRead: 0.0145, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    // OpenRouter pool (11)
    {
        id: "deepseek/deepseek-v4-flash",
        name: "DeepSeek V4 Flash (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 131_072,
        cost: { input: 0.1, output: 0.2, cacheRead: 0.02, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 384_000,
        cost: { input: 0.44, output: 0.87, cacheRead: 0.004, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "google/gemma-4-26b-a4b-it",
        name: "Gemma 4 26B (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 32_768,
        cost: { input: 0.06, output: 0.33, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "google/gemma-4-31b-it",
        name: "Gemma 4 31B (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 8_192,
        cost: { input: 0.12, output: 0.36, cacheRead: 0.09, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "moonshotai/kimi-k2.6:free",
        name: "Kimi K2.6 Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 262_144,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "poolside/laguna-m.1:free",
        name: "Laguna M.1 Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 32_768,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "google/gemma-4-26b-a4b-it:free",
        name: "Gemma 4 26B Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 32_768,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "google/gemma-4-31b-it:free",
        name: "Gemma 4 31B Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 262_144,
        maxTokens: 32_768,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "nvidia/nemotron-3-super-120b-a12b:free",
        name: "Nemotron 3 Super Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 262_144,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "nvidia/nemotron-3-ultra-550b-a55b:free",
        name: "Nemotron 3 Ultra Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "qwen/qwen3.6-plus-preview:free",
        name: "Qwen 3.6 Plus Preview Free (Pool)",
        reasoning: true,
        input: ["text"],
        contextWindow: 1_000_000,
        maxTokens: 128_000,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    // Antigravity (9)
    {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6 (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 64_000,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "claude-opus-4-6-thinking",
        name: "Claude Opus 4.6 Thinking (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 128_000,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_048_576,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_048_576,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_048_576,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3.1-flash-image",
        name: "Gemini 3.1 Flash Image (Antigravity)",
        reasoning: false,
        input: ["text", "image"],
        contextWindow: 1_048_576,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gemini-3.6-flash",
        name: "Gemini 3.6 Flash (Antigravity)",
        reasoning: true,
        input: ["text", "image"],
        contextWindow: 1_000_000,
        maxTokens: 65_536,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
    {
        id: "gpt-oss-120b-medium",
        name: "GPT-OSS 120B Medium (Antigravity)",
        reasoning: true,
        input: ["text"],
        contextWindow: 128_000,
        maxTokens: 32_768,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        compat: NO_DEV_ROLE_COMPAT,
    },
];
