import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import {
    existsSync,
    mkdirSync,
    mkdtempSync,
    readFileSync,
    rmSync,
    writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { Theme } from '@earendil-works/pi-coding-agent';
import {
    buildSandboxShellEnv,
    envSandboxStatus,
    ensureGitignored,
    explicitlyDisabled,
    GHOST_PATTERNS,
    _resetGitignoreEnsured,
    loadSandboxConfig,
    loadSessionSandboxStatus,
    renderSandboxWidget,
    saveSessionSandboxStatus,
    type LoadSandboxConfigResult,
} from './index';

const ENV_OVERRIDE_KEY = 'PI_SANDBOX_SESSION_STATUS';

function withEnv<T>(key: string, value: string | undefined, fn: () => T): T {
    const previous = process.env[key];
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
    try {
        return fn();
    } finally {
        if (previous === undefined) delete process.env[key];
        else process.env[key] = previous;
    }
}

function fakeTheme(): Theme {
    return { fg: (color: string, text: string) => `fg:${color}:${text}` } as unknown as Theme;
}

const emptySettingsManager = {
    getGlobalSettings: () => ({}),
    getProjectSettings: () => ({}),
};

describe('loadSandboxConfig', () => {
    let root: string;
    let agentDir: string;
    let cwd: string;

    beforeEach(() => {
        root = mkdtempSync(join(tmpdir(), 'sandbox-config-test-'));
        agentDir = join(root, 'agent');
        cwd = join(root, 'project');
        mkdirSync(agentDir, { recursive: true });
        mkdirSync(cwd, { recursive: true });
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
    });

    it('throws for malformed global legacy config', () => {
        writeFileSync(join(agentDir, 'sandbox.json'), '{ invalid');

        expect(() =>
            loadSandboxConfig(cwd, { agentDir, settingsManager: emptySettingsManager }),
        ).toThrow('Could not parse sandbox config');
    });

    it('throws for malformed project legacy config', () => {
        mkdirSync(join(cwd, '.pi'), { recursive: true });
        writeFileSync(join(cwd, '.pi', 'sandbox.json'), '{ invalid');

        expect(() =>
            loadSandboxConfig(cwd, { agentDir, settingsManager: emptySettingsManager }),
        ).toThrow('Could not parse sandbox config');
    });

    it('throws for malformed global and project settings values', () => {
        expect(() =>
            loadSandboxConfig(cwd, {
                agentDir,
                settingsManager: {
                    getGlobalSettings: () => ({ sandbox: 'invalid' }),
                    getProjectSettings: () => ({}),
                },
            }),
        ).toThrow('Invalid global sandbox settings');

        expect(() =>
            loadSandboxConfig(cwd, {
                agentDir,
                settingsManager: {
                    getGlobalSettings: () => ({}),
                    getProjectSettings: () => ({ sandbox: [] }),
                },
            }),
        ).toThrow('Invalid project sandbox settings');
    });

    it('throws when settings loading fails', () => {
        expect(() =>
            loadSandboxConfig(cwd, {
                agentDir,
                settingsManager: {
                    getGlobalSettings: () => {
                        throw new Error('settings unavailable');
                    },
                    getProjectSettings: () => ({}),
                },
            }),
        ).toThrow('Could not load sandbox settings: settings unavailable');
    });
});

describe('ensureGitignored', () => {
    let tmpDir: string;

    beforeEach(() => {
        tmpDir = mkdtempSync(join(tmpdir(), 'sandbox-test-'));
        _resetGitignoreEnsured();
    });

    afterEach(() => {
        rmSync(tmpDir, { recursive: true, force: true });
    });

    it('creates .gitignore with all patterns when it does not exist', () => {
        ensureGitignored(tmpDir);

        const gitignorePath = join(tmpDir, '.gitignore');
        expect(existsSync(gitignorePath)).toBe(true);

        const content = readFileSync(gitignorePath, 'utf-8');
        for (const pattern of GHOST_PATTERNS) {
            expect(content).toContain(pattern);
        }
        expect(content).toContain(
            '# Sandbox ghost files (auto-generated by pi sandbox extension)',
        );
    });

    it('adds only missing patterns to existing .gitignore', () => {
        // Pre-populate .gitignore with some patterns already present
        const preExisting = '.bashrc\n.gitconfig\nnode_modules/\n';
        const gitignorePath = join(tmpDir, '.gitignore');
        Bun.write(gitignorePath, preExisting);

        ensureGitignored(tmpDir);

        const content = readFileSync(gitignorePath, 'utf-8');
        // Should still have pre-existing content
        expect(content).toContain('node_modules/');
        // Should have header
        expect(content).toContain(
            '# Sandbox ghost files (auto-generated by pi sandbox extension)',
        );
        // Should have patterns not already there
        expect(content).toContain('.gitmodules');
        expect(content).toContain('.vscode/');
    });

    it('does not write again if called twice (flag guard)', () => {
        ensureGitignored(tmpDir);

        const gitignorePath = join(tmpDir, '.gitignore');
        const afterFirst = readFileSync(gitignorePath, 'utf-8');

        ensureGitignored(tmpDir);

        const afterSecond = readFileSync(gitignorePath, 'utf-8');
        expect(afterSecond).toBe(afterFirst);
    });

    it('does nothing if all patterns already present', () => {
        const gitignorePath = join(tmpDir, '.gitignore');
        Bun.write(gitignorePath, GHOST_PATTERNS.join('\n'));

        ensureGitignored(tmpDir);

        const content = readFileSync(gitignorePath, 'utf-8');
        // Header not added because nothing was missing
        expect(content).not.toContain('auto-generated by pi sandbox extension');
        // No duplicate patterns
        const lines = content.split('\n').filter((l) => l.trim());
        const unique = new Set(lines);
        expect(unique.size).toBe(lines.length);
    });
});

describe('buildSandboxShellEnv', () => {
    it('prepends agent bin dir to PATH when missing', () => {
        const env = buildSandboxShellEnv(
            { PATH: '/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.PATH).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });

    it('does not duplicate agent bin dir when already present', () => {
        const env = buildSandboxShellEnv(
            { PATH: '~/.pi/agent/bin:/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.PATH).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });

    it('preserves alternate path key casing', () => {
        const env = buildSandboxShellEnv(
            { Path: '/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.Path).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });
});

describe('renderSandboxWidget', () => {
    it('always renders the off state with warning color and ⚠ glyph', () => {
        const rendered = renderSandboxWidget(fakeTheme(), 'off');
        expect(rendered).not.toBeNull();
        expect(rendered).toContain('⚠');
        expect(rendered).toContain('fg:warning:');
    });

    it('embeds the shield icon when on', () => {
        expect(renderSandboxWidget(fakeTheme(), 'on')).toContain('🛡️');
    });

    it('keeps the label dim', () => {
        expect(renderSandboxWidget(fakeTheme(), 'on')).toContain('fg:dim:');
    });

    it('colors only the on value accent', () => {
        expect(renderSandboxWidget(fakeTheme(), 'on')).toContain('fg:accent:on');
    });

    it('colors only the restricted value warning', () => {
        expect(renderSandboxWidget(fakeTheme(), 'restricted')).toContain(
            'fg:warning:restricted',
        );
    });

    it('colors only the error value danger', () => {
        expect(renderSandboxWidget(fakeTheme(), 'error')).toContain(
            'fg:error:error',
        );
    });
});

describe('loadSessionSandboxStatus', () => {
    let root: string;
    let sessionDir: string;

    beforeEach(() => {
        root = mkdtempSync(join(tmpdir(), 'sandbox-session-state-'));
        sessionDir = join(root, 'session');
        mkdirSync(sessionDir, { recursive: true });
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
    });

    it('returns undefined when the state file is missing', () => {
        expect(loadSessionSandboxStatus(sessionDir)).toBeUndefined();
    });

    it('returns "enabled" for { enabled: true }', () => {
        writeFileSync(
            join(sessionDir, 'sandbox-state.json'),
            JSON.stringify({ enabled: true, updatedAt: '2026-01-01T00:00:00.000Z' }),
        );
        expect(loadSessionSandboxStatus(sessionDir)).toBe('enabled');
    });

    it('returns "disabled" for { enabled: false }', () => {
        writeFileSync(
            join(sessionDir, 'sandbox-state.json'),
            JSON.stringify({ enabled: false, updatedAt: '2026-01-01T00:00:00.000Z' }),
        );
        expect(loadSessionSandboxStatus(sessionDir)).toBe('disabled');
    });

    it('returns undefined for malformed JSON', () => {
        writeFileSync(join(sessionDir, 'sandbox-state.json'), '{ invalid');
        expect(loadSessionSandboxStatus(sessionDir)).toBeUndefined();
    });

    it('returns undefined when enabled field is missing', () => {
        writeFileSync(
            join(sessionDir, 'sandbox-state.json'),
            JSON.stringify({ updatedAt: '2026-01-01T00:00:00.000Z' }),
        );
        expect(loadSessionSandboxStatus(sessionDir)).toBeUndefined();
    });

    it('returns undefined when enabled is not boolean', () => {
        writeFileSync(
            join(sessionDir, 'sandbox-state.json'),
            JSON.stringify({ enabled: 'true' }),
        );
        expect(loadSessionSandboxStatus(sessionDir)).toBeUndefined();
    });

    it('returns undefined when sessionDir is empty or null', () => {
        expect(loadSessionSandboxStatus('')).toBeUndefined();
    });

    it('returns undefined when sessionDir does not exist', () => {
        expect(loadSessionSandboxStatus(join(root, 'missing'))).toBeUndefined();
    });
});

describe('saveSessionSandboxStatus', () => {
    let root: string;
    let sessionDir: string;

    beforeEach(() => {
        root = mkdtempSync(join(tmpdir(), 'sandbox-session-state-save-'));
        sessionDir = join(root, 'session');
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
    });

    it('writes enabled status to sandbox-state.json', () => {
        saveSessionSandboxStatus(sessionDir, 'enabled');
        const file = join(sessionDir, 'sandbox-state.json');
        expect(existsSync(file)).toBe(true);
        const parsed = JSON.parse(readFileSync(file, 'utf-8'));
        expect(parsed.enabled).toBe(true);
        expect(typeof parsed.updatedAt).toBe('string');
        expect(() => new Date(parsed.updatedAt).toISOString()).not.toThrow();
    });

    it('writes disabled status to sandbox-state.json', () => {
        saveSessionSandboxStatus(sessionDir, 'disabled');
        const file = join(sessionDir, 'sandbox-state.json');
        const parsed = JSON.parse(readFileSync(file, 'utf-8'));
        expect(parsed.enabled).toBe(false);
    });

    it('overwrites an existing file atomically', () => {
        mkdirSync(sessionDir, { recursive: true });
        writeFileSync(
            join(sessionDir, 'sandbox-state.json'),
            JSON.stringify({ enabled: true, updatedAt: 'old' }),
        );
        saveSessionSandboxStatus(sessionDir, 'disabled');
        const parsed = JSON.parse(
            readFileSync(join(sessionDir, 'sandbox-state.json'), 'utf-8'),
        );
        expect(parsed.enabled).toBe(false);
        expect(parsed.updatedAt).not.toBe('old');
    });

    it('no-ops when sessionDir is empty', () => {
        expect(() => saveSessionSandboxStatus('', 'enabled')).not.toThrow();
    });

    it('no-ops when sessionDir is unwritable instead of throwing', () => {
        // Root path used as a file to make the dir creation fail.
        const blocker = join(root, 'blocker');
        writeFileSync(blocker, 'not a dir');
        expect(() => saveSessionSandboxStatus(blocker, 'enabled')).not.toThrow();
    });
});

describe('envSandboxStatus', () => {
    afterEach(() => {
        delete process.env[ENV_OVERRIDE_KEY];
    });

    it('returns undefined when env var is unset', () => {
        delete process.env[ENV_OVERRIDE_KEY];
        expect(envSandboxStatus()).toBeUndefined();
    });

    it('returns "enabled" for "enabled"', () => {
        withEnv(ENV_OVERRIDE_KEY, 'enabled', () => {
            expect(envSandboxStatus()).toBe('enabled');
        });
    });

    it('returns "disabled" for "disabled"', () => {
        withEnv(ENV_OVERRIDE_KEY, 'disabled', () => {
            expect(envSandboxStatus()).toBe('disabled');
        });
    });

    it('is case-insensitive', () => {
        withEnv(ENV_OVERRIDE_KEY, 'ENABLED', () => {
            expect(envSandboxStatus()).toBe('enabled');
        });
        withEnv(ENV_OVERRIDE_KEY, 'Disabled', () => {
            expect(envSandboxStatus()).toBe('disabled');
        });
    });

    it('returns undefined for any other value', () => {
        withEnv(ENV_OVERRIDE_KEY, 'true', () => {
            expect(envSandboxStatus()).toBeUndefined();
        });
        withEnv(ENV_OVERRIDE_KEY, '', () => {
            expect(envSandboxStatus()).toBeUndefined();
        });
        withEnv(ENV_OVERRIDE_KEY, 'maybe', () => {
            expect(envSandboxStatus()).toBeUndefined();
        });
    });
});

describe('loadSandboxConfig resolution priority', () => {
    let root: string;
    let agentDir: string;
    let cwd: string;
    let sessionDir: string;

    beforeEach(() => {
        root = mkdtempSync(join(tmpdir(), 'sandbox-config-resolution-'));
        agentDir = join(root, 'agent');
        cwd = join(root, 'project');
        sessionDir = join(root, 'sessions', 'abc');
        mkdirSync(agentDir, { recursive: true });
        mkdirSync(cwd, { recursive: true });
        mkdirSync(sessionDir, { recursive: true });
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
        delete process.env[ENV_OVERRIDE_KEY];
    });

    function load(opts: Parameters<typeof loadSandboxConfig>[1] = {}) {
        return loadSandboxConfig(cwd, {
            agentDir,
            settingsManager: emptySettingsManager,
            ...opts,
        });
    }

    it('returns source "default" with enabled=false when nothing overrides', () => {
        const result = load();
        expect(result.source).toBe('default');
        expect(result.config.enabled).toBe(false);
    });

    it('global enabled=true wins over default with source "global-config"', () => {
        writeFileSync(
            join(agentDir, 'sandbox.json'),
            JSON.stringify({ enabled: true }),
        );
        const result = load();
        expect(result.source).toBe('global-config');
        expect(result.config.enabled).toBe(true);
    });

    it('project enabled=false wins over global enabled=true with source "project-config"', () => {
        writeFileSync(
            join(agentDir, 'sandbox.json'),
            JSON.stringify({ enabled: true }),
        );
        mkdirSync(join(cwd, '.pi'));
        writeFileSync(
            join(cwd, '.pi', 'sandbox.json'),
            JSON.stringify({ enabled: false }),
        );
        const result = load();
        expect(result.source).toBe('project-config');
        expect(result.config.enabled).toBe(false);
    });

    it('session file enabled=true wins over project enabled=false with source "session-file"', () => {
        mkdirSync(join(cwd, '.pi'));
        writeFileSync(
            join(cwd, '.pi', 'sandbox.json'),
            JSON.stringify({ enabled: false }),
        );
        saveSessionSandboxStatus(sessionDir, 'enabled');
        const result = load({ sessionDir });
        expect(result.source).toBe('session-file');
        expect(result.config.enabled).toBe(true);
    });

    it('env "disabled" wins over session file "enabled" with source "env"', () => {
        saveSessionSandboxStatus(sessionDir, 'enabled');
        const result = load({
            sessionDir,
            envOverride: envSandboxStatus(),
        });
        withEnv(ENV_OVERRIDE_KEY, 'disabled', () => {
            const overridden = load({
                sessionDir,
                envOverride: envSandboxStatus(),
            });
            expect(overridden.source).toBe('env');
            expect(overridden.config.enabled).toBe(false);
        });
        expect(result.source).toBe('session-file');
    });

    it('does not override network or filesystem fields with session/env overrides', () => {
        mkdirSync(join(cwd, '.pi'));
        writeFileSync(
            join(cwd, '.pi', 'sandbox.json'),
            JSON.stringify({
                enabled: true,
                network: { allowedDomains: ['example.com'] },
                filesystem: { denyRead: ['.secret'] },
            }),
        );
        saveSessionSandboxStatus(sessionDir, 'disabled');
        const result = load({ sessionDir });
        expect(result.config.enabled).toBe(false);
        expect(result.config.network?.allowedDomains).toContain('example.com');
        expect(result.config.filesystem?.denyRead).toContain('.secret');
    });
});

describe('explicitlyDisabled', () => {
    function result(
        source: LoadSandboxConfigResult['source'],
        enabled: boolean,
    ): LoadSandboxConfigResult {
        return {
            config: { enabled } as LoadSandboxConfigResult['config'],
            source,
        };
    }

    it('returns false when source is "default"', () => {
        expect(explicitlyDisabled(result('default', false))).toBe(false);
    });

    it('returns true when source is non-default and enabled is false', () => {
        expect(explicitlyDisabled(result('env', false))).toBe(true);
        expect(explicitlyDisabled(result('session-file', false))).toBe(true);
        expect(explicitlyDisabled(result('project-config', false))).toBe(true);
        expect(explicitlyDisabled(result('global-config', false))).toBe(true);
    });

    it('returns false when enabled is true', () => {
        expect(explicitlyDisabled(result('project-config', true))).toBe(false);
        expect(explicitlyDisabled(result('env', true))).toBe(false);
    });
});
