import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
    buildSandboxShellEnv,
    ensureGitignored,
    GHOST_PATTERNS,
    _resetGitignoreEnsured,
} from './index';

describe('ensureGitignored', () => {
    let tmpDir: string;

    beforeEach(() => {
        tmpDir = mkdtempSync(join(tmpdir(), 'sandbox-test-'));
        _resetGitignoreEnsured();
    });

    afterEach(() => {
        rmSync(tmpDir, { recursive: true, force: true });
    });

    it('creates .gitignore with all patterns when it does not exist', () => {
        ensureGitignored(tmpDir);

        const gitignorePath = join(tmpDir, '.gitignore');
        expect(existsSync(gitignorePath)).toBe(true);

        const content = readFileSync(gitignorePath, 'utf-8');
        for (const pattern of GHOST_PATTERNS) {
            expect(content).toContain(pattern);
        }
        expect(content).toContain(
            '# Sandbox ghost files (auto-generated by pi sandbox extension)',
        );
    });

    it('adds only missing patterns to existing .gitignore', () => {
        // Pre-populate .gitignore with some patterns already present
        const preExisting = '.bashrc\n.gitconfig\nnode_modules/\n';
        const gitignorePath = join(tmpDir, '.gitignore');
        Bun.write(gitignorePath, preExisting);

        ensureGitignored(tmpDir);

        const content = readFileSync(gitignorePath, 'utf-8');
        // Should still have pre-existing content
        expect(content).toContain('node_modules/');
        // Should have header
        expect(content).toContain(
            '# Sandbox ghost files (auto-generated by pi sandbox extension)',
        );
        // Should have patterns not already there
        expect(content).toContain('.gitmodules');
        expect(content).toContain('.vscode/');
    });

    it('does not write again if called twice (flag guard)', () => {
        ensureGitignored(tmpDir);

        const gitignorePath = join(tmpDir, '.gitignore');
        const afterFirst = readFileSync(gitignorePath, 'utf-8');

        ensureGitignored(tmpDir);

        const afterSecond = readFileSync(gitignorePath, 'utf-8');
        expect(afterSecond).toBe(afterFirst);
    });

    it('does nothing if all patterns already present', () => {
        const gitignorePath = join(tmpDir, '.gitignore');
        Bun.write(gitignorePath, GHOST_PATTERNS.join('\n'));

        ensureGitignored(tmpDir);

        const content = readFileSync(gitignorePath, 'utf-8');
        // Header not added because nothing was missing
        expect(content).not.toContain('auto-generated by pi sandbox extension');
        // No duplicate patterns
        const lines = content.split('\n').filter((l) => l.trim());
        const unique = new Set(lines);
        expect(unique.size).toBe(lines.length);
    });
});

describe('buildSandboxShellEnv', () => {
    it('prepends agent bin dir to PATH when missing', () => {
        const env = buildSandboxShellEnv(
            { PATH: '/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.PATH).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });

    it('does not duplicate agent bin dir when already present', () => {
        const env = buildSandboxShellEnv(
            { PATH: '~/.pi/agent/bin:/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.PATH).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });

    it('preserves alternate path key casing', () => {
        const env = buildSandboxShellEnv(
            { Path: '/usr/local/bin:/usr/bin' },
            '~/.pi/agent',
        );
        expect(env.Path).toBe(
            '~/.pi/agent/bin:/usr/local/bin:/usr/bin',
        );
    });
});
