import { createHash } from "node:crypto";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import type { Readable } from "node:stream";
import { isDeepStrictEqual } from "node:util";
import type {
    SandboxAdmission,
    SandboxAdmissionReport,
} from "../../_shared/sandbox-runtime/admission-protocol.ts";
import { SandboxExecutionError, type SandboxPolicy } from "./contracts.ts";

export type {
    SandboxAdmission,
    SandboxAdmissionReport,
} from "../../_shared/sandbox-runtime/admission-protocol.ts";

export const MAX_ADMISSION_BYTES = 1_048_576;
// Protocol-owned names generated by the Linux network proxy. This list grants
// no host inheritance and is available only when the submitted policy uses it.
const PROXY_ENVIRONMENT_NAMES = [
    "CODEX_NETWORK_PROXY_ACTIVE",
    "CODEX_NETWORK_ALLOW_LOCAL_BINDING",
    "ELECTRON_GET_USE_PROXY",
    "NODE_USE_ENV_PROXY",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "http_proxy",
    "https_proxy",
    "YARN_HTTP_PROXY",
    "YARN_HTTPS_PROXY",
    "npm_config_http_proxy",
    "npm_config_https_proxy",
    "npm_config_proxy",
    "NPM_CONFIG_HTTP_PROXY",
    "NPM_CONFIG_HTTPS_PROXY",
    "NPM_CONFIG_PROXY",
    "BUNDLE_HTTP_PROXY",
    "BUNDLE_HTTPS_PROXY",
    "PIP_PROXY",
    "DOCKER_HTTP_PROXY",
    "DOCKER_HTTPS_PROXY",
    "WS_PROXY",
    "WSS_PROXY",
    "ws_proxy",
    "wss_proxy",
    "NO_PROXY",
    "no_proxy",
    "npm_config_noproxy",
    "NPM_CONFIG_NOPROXY",
    "YARN_NO_PROXY",
    "BUNDLE_NO_PROXY",
    "ALL_PROXY",
    "all_proxy",
    "FTP_PROXY",
    "ftp_proxy",
] as const;
function record(value: unknown): value is Record<string, unknown> {
    return value !== null && typeof value === "object" && !Array.isArray(value);
}
function strings(value: unknown): value is string[] {
    return (
        Array.isArray(value) &&
        value.every((item) => typeof item === "string" && !item.includes("\0"))
    );
}
function digest(value: unknown): value is string {
    return typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
}
function path(value: unknown): value is string {
    return (
        typeof value === "string" && isAbsolute(value) && !value.includes("\0")
    );
}
function failure(message: string, cause?: unknown): SandboxExecutionError {
    return new SandboxExecutionError("protocol-error", {
        diagnostic: `Invalid sandbox admission: ${message}`,
        cause,
    });
}

function kernelMount(
    value: unknown,
): value is SandboxAdmissionReport["kernelMounts"][number] {
    return (
        record(value) &&
        path(value.destination) &&
        path(value.root) &&
        typeof value.source === "string" &&
        !value.source.includes("\0") &&
        typeof value.filesystem === "string" &&
        value.filesystem.length > 0 &&
        (value.access === "ro" || value.access === "rw")
    );
}

export function parseSandboxAdmissionReport(
    value: unknown,
): SandboxAdmissionReport {
    if (!record(value) || (value.schema !== 1 && value.schema !== 2))
        throw failure("unsupported schema");
    const {
        runtime,
        filesystem,
        network,
        resources,
        environment,
        home,
        tmp,
        docker,
    } = value;
    if (
        !record(runtime) ||
        runtime.target !== "x86_64-unknown-linux-gnu" ||
        typeof runtime.version !== "string" ||
        !runtime.version ||
        !digest(runtime.manifestSha256) ||
        !["shell", "analysis"].includes(String(runtime.component)) ||
        !digest(value.helperSha256)
    )
        throw failure("invalid runtime identity");
    if (
        !record(filesystem) ||
        ![
            "allowRead",
            "denyRead",
            "denyReadGlobs",
            "allowWrite",
            "denyWrite",
            "denyWriteGlobs",
        ].every((key) => strings(filesystem[key]))
    )
        throw failure("invalid filesystem rules");
    if (
        !record(network) ||
        !["deny-all", "domain-allowlist"].includes(String(network.mode)) ||
        !["allow", "allowHost", "deny"].every((key) => strings(network[key])) ||
        typeof network.allowLocalBinding !== "boolean"
    )
        throw failure("invalid network rules");
    const mediatedDirectTcp = network.mediatedDirectTcp;
    const validDirectPorts =
        record(mediatedDirectTcp) &&
        Object.keys(mediatedDirectTcp).every((key) => key === "ports") &&
        Array.isArray(mediatedDirectTcp.ports) &&
        mediatedDirectTcp.ports.length > 0 &&
        mediatedDirectTcp.ports.length <= 64 &&
        mediatedDirectTcp.ports.every(
            (port, index, ports) =>
                Number.isInteger(port) &&
                port >= 1 &&
                port <= 65_535 &&
                (index === 0 || ports[index - 1]! < port),
        );
    if (
        (value.schema === 1 && mediatedDirectTcp !== undefined) ||
        (value.schema === 2 && !validDirectPorts)
    )
        throw failure("invalid mediated direct TCP grant");
    if (
        !record(resources) ||
        !strings(resources.unixSockets) ||
        !Array.isArray(resources.tcpPublications) ||
        !resources.tcpPublications.every(
            (item) =>
                record(item) &&
                item.transport === "tcp" &&
                ["host", "lan"].includes(String(item.scope)) &&
                typeof item.listen === "string" &&
                typeof item.target === "string",
        )
    )
        throw failure("invalid resources");
    if (
        !strings(value.path) ||
        !value.path.every(path) ||
        !record(environment) ||
        !["inherit", "set", "deny"].every((key) => strings(environment[key]))
    )
        throw failure("invalid environment");
    if (
        !record(home) ||
        !path(home.path) ||
        home.namespace !== "lease-private" ||
        !record(tmp) ||
        tmp.path !== "/tmp" ||
        !["host", "lease-private"].includes(String(tmp.namespace))
    )
        throw failure("invalid private namespaces");
    if (
        !record(docker) ||
        !["disabled", "targeted", "full"].includes(String(docker.mode)) ||
        (docker.mode !== "disabled" && typeof docker.endpoint !== "string") ||
        (docker.mode === "targeted" &&
            (!Array.isArray(docker.targets) ||
                !docker.targets.every(
                    (target) =>
                        record(target) &&
                        record(target.selector) &&
                        typeof target.allowUnsafeTarget === "boolean" &&
                        (target.operations === undefined ||
                            strings(target.operations)),
                )))
    )
        throw failure("invalid Docker rules");
    if (
        !Array.isArray(value.mounts) ||
        !value.mounts.every(
            (mount) =>
                record(mount) &&
                path(mount.source) &&
                path(mount.destination) &&
                ["ro", "rw"].includes(String(mount.access)) &&
                ["runtime", "policy", "internal"].includes(
                    String(mount.origin),
                ) &&
                (!(
                    mount.destination === "/__zerobox" ||
                    mount.destination.startsWith("/__zerobox/")
                ) ||
                    (mount.origin !== "policy" && mount.access === "ro")),
        ) ||
        !value.mounts.some(
            (mount: unknown) =>
                record(mount) &&
                mount.destination === "/__zerobox/runtime" &&
                mount.origin === "runtime" &&
                mount.access === "ro",
        )
    )
        throw failure("invalid runtime mounts");
    if (
        value.pathAliases !== undefined &&
        (!Array.isArray(value.pathAliases) ||
            !value.pathAliases.every(
                (alias) =>
                    record(alias) &&
                    path(alias.destination) &&
                    path(alias.target) &&
                    resolve(alias.destination) === alias.destination &&
                    resolve(alias.target) === alias.target &&
                    alias.destination !== "/" &&
                    alias.target !== "/" &&
                    ![alias.destination, alias.target].some(
                        (value) =>
                            value === "/__zerobox" ||
                            value.startsWith("/__zerobox/"),
                    ) &&
                    typeof alias.directory === "boolean",
            ))
    )
        throw failure("invalid path aliases");
    if (
        !Array.isArray(value.kernelMounts) ||
        !value.kernelMounts.every(kernelMount)
    )
        throw failure("missing or invalid kernel mount evidence");
    for (const destination of [
        "/__zerobox/runtime",
        ...(runtime.component === "analysis" ? ["/__zerobox/analysis"] : []),
    ]) {
        const matches = value.kernelMounts.filter(
            (mount) => mount.destination === destination,
        );
        if (matches.length !== 1 || matches[0]?.access !== "ro")
            throw failure(
                "runtime mount is absent or writable in the kernel table",
            );
    }
    if (
        runtime.component === "shell" &&
        value.kernelMounts.some(
            (mount) => mount.destination === "/__zerobox/analysis",
        )
    )
        throw failure("unexpected Analysis kernel mount");
    // Every member above is validated before crossing the wire-format boundary.
    return value as unknown as SandboxAdmissionReport;
}

export function assertAdmissionMatchesPolicy(
    admission: SandboxAdmission,
    policy: SandboxPolicy,
    runtime: {
        manifestSha256: string;
        helperSha256: string;
        version: string;
        target: string;
        component: "shell" | "analysis";
        shellRoot: string;
        analysisRoot: string;
    },
): void {
    const report = admission.report;
    const equal = (left: readonly string[], right: readonly string[]) =>
        JSON.stringify([...new Set(left)].sort()) ===
        JSON.stringify([...new Set(right)].sort());
    const equalPorts = (left: readonly number[], right: readonly number[]) =>
        JSON.stringify([...new Set(left)].toSorted((a, b) => a - b)) ===
        JSON.stringify([...new Set(right)].toSorted((a, b) => a - b));
    if (
        report.runtime.manifestSha256 !== runtime.manifestSha256 ||
        report.runtime.component !== runtime.component ||
        report.runtime.version !== runtime.version ||
        report.runtime.target !== runtime.target ||
        report.helperSha256 !== runtime.helperSha256
    )
        throw failure("runtime identity differs from the pinned bundle");
    for (const [destination, source] of [
        ["/__zerobox/runtime", runtime.shellRoot],
        ...(runtime.component === "analysis"
            ? [["/__zerobox/analysis", runtime.analysisRoot]]
            : []),
    ]) {
        if (
            !report.mounts.some(
                (mount) =>
                    mount.destination === destination &&
                    mount.source === source &&
                    mount.origin === "runtime" &&
                    mount.access === "ro",
            )
        )
            throw failure("runtime mount differs from the pinned bundle");
    }
    for (const key of ["allowRead", "allowWrite"] as const)
        if (!equal(report.filesystem[key], policy.filesystem[key]))
            throw failure(
                `filesystem.${key} differs from the submitted policy`,
            );
    for (const key of [
        "denyRead",
        "denyReadGlobs",
        "denyWrite",
        "denyWriteGlobs",
    ] as const)
        if (
            policy.filesystem[key].some(
                (rule) => !report.filesystem[key].includes(rule),
            )
        )
            throw failure(
                `filesystem.${key} differs from the submitted policy`,
            );
    const within = (candidate: string, root: string) => {
        const suffix = relative(resolve(root), resolve(candidate));
        return (
            suffix === "" ||
            (!suffix.startsWith("../") &&
                suffix !== ".." &&
                !isAbsolute(suffix))
        );
    };
    const control = report.mounts.find(
        (mount) =>
            mount.destination === "/__zerobox" &&
            mount.origin === "internal" &&
            mount.access === "ro",
    );
    const internalRoot = control ? dirname(dirname(control.source)) : undefined;
    const publicGrants = [
        ...policy.filesystem.allowRead,
        ...policy.filesystem.allowWrite,
    ];
    for (const alias of report.pathAliases ?? []) {
        // An intermediate alias creates an empty directory, not a host read
        // grant. Every actual bind is checked independently below.
        if (
            !publicGrants.some(
                (root) =>
                    within(alias.destination, root) ||
                    within(root, alias.destination),
            )
        )
            throw failure("path alias exceeds the submitted filesystem grants");
    }
    for (const mount of report.mounts) {
        if (mount.origin === "runtime") {
            const source =
                mount.destination === "/__zerobox/runtime"
                    ? runtime.shellRoot
                    : mount.destination ===
                        "/__zerobox/runtime/libexec/zerobox-linux-sandbox"
                      ? join(runtime.shellRoot, "libexec/zerobox-linux-sandbox")
                      : mount.destination === "/__zerobox/analysis" &&
                          runtime.component === "analysis"
                        ? runtime.analysisRoot
                        : undefined;
            if (source !== mount.source || mount.access !== "ro")
                throw failure("unexpected runtime mount");
            continue;
        }
        if (mount.origin === "internal") {
            const namespace =
                mount.access === "rw" &&
                (mount.destination === report.home.path ||
                    (mount.destination === "/tmp" &&
                        report.tmp.namespace === "lease-private")) &&
                policy.filesystem.allowWrite.some((root) =>
                    within(mount.source, root),
                );
            const view =
                internalRoot &&
                within(mount.source, internalRoot) &&
                policy.filesystem.allowWrite.some((root) =>
                    within(mount.destination, root),
                );
            const resourceView =
                internalRoot &&
                mount.access === "rw" &&
                within(mount.source, internalRoot) &&
                policy.resources?.unixSockets.some(
                    (socket) =>
                        dirname(resolve(socket)) === resolve(mount.destination),
                );
            const targetEnvironment =
                control &&
                mount.access === "ro" &&
                mount.source === mount.destination &&
                mount.source !== dirname(control.source) &&
                within(mount.source, dirname(control.source));
            const shellAlias =
                internalRoot &&
                mount.access === "ro" &&
                ((mount.destination === "/bin" &&
                    mount.source === join(internalRoot, "a/bin")) ||
                    (mount.destination === "/usr/bin" &&
                        mount.source === join(internalRoot, "a/usr/bin")));
            if (
                mount !== control &&
                !namespace &&
                !view &&
                !resourceView &&
                !targetEnvironment &&
                !shellAlias
            )
                throw failure(
                    "internal mount exceeds the submitted filesystem grants",
                );
            continue;
        }
        if (
            mount.source === mount.destination &&
            mount.access === "rw" &&
            policy.resources?.unixSockets.includes(mount.source)
        )
            continue;
        const grants =
            mount.access === "rw"
                ? policy.filesystem.allowWrite
                : [
                      ...policy.filesystem.allowRead,
                      ...policy.filesystem.allowWrite,
                  ];
        if (
            ![mount.source, mount.destination].every((candidate) =>
                grants.some((root) => within(candidate, root)),
            )
        )
            throw failure(
                "policy mount exceeds the submitted filesystem grants",
            );
    }
    for (const key of ["allow", "allowHost", "deny"] as const)
        if (!equal(report.network[key], policy.network[key]))
            throw failure(`network.${key} differs from the submitted policy`);
    if (report.network.mode !== policy.network.mode)
        throw failure("network mode differs from the submitted policy");
    const submittedDirect = policy.network.mediatedDirectTcp;
    const reportedDirect = report.network.mediatedDirectTcp;
    if (
        submittedDirect === undefined
            ? report.schema !== 1 || reportedDirect !== undefined
            : report.schema !== 2 ||
              reportedDirect === undefined ||
              !equalPorts(reportedDirect.ports, submittedDirect.ports)
    )
        throw failure(
            "mediated direct TCP ports differ from the submitted policy schema",
        );
    if (
        report.network.allowLocalBinding !==
        (policy.network.allowLocalBinding ?? false)
    )
        throw failure("local binding differs from the submitted policy");
    if (report.home.path !== policy.environment.set.HOME)
        throw failure("HOME differs from the submitted policy");
    if (report.tmp.namespace !== policy.tmpNamespace)
        throw failure("temporary namespace differs from the submitted policy");
    if (
        JSON.stringify(report.path) !==
        JSON.stringify(
            (policy.environment.set.PATH ?? "").split(":").filter(Boolean),
        )
    )
        throw failure("PATH differs from the submitted policy");
    const denied = new Set(policy.environment.deny);
    const requestedNames = Object.keys(policy.environment.set).filter(
        (name) => !denied.has(name),
    );
    const allowedNames = new Set<string>([
        ...requestedNames,
        ...(policy.network.mode === "deny-all"
            ? ["CODEX_SANDBOX_NETWORK_DISABLED"]
            : PROXY_ENVIRONMENT_NAMES),
        ...(policy.docker.mode !== "disabled" ? ["DOCKER_HOST"] : []),
    ]);
    if (
        report.environment.inherit.some(
            (name) =>
                !policy.environment.inherit.includes(name) || denied.has(name),
        ) ||
        requestedNames.some((name) => !report.environment.set.includes(name)) ||
        report.environment.set.some(
            (name) => !allowedNames.has(name) || denied.has(name),
        ) ||
        !equal(report.environment.deny, policy.environment.deny)
    )
        throw failure(
            "effective environment names differ from the submitted policy",
        );
    if (
        !equal(
            report.resources.unixSockets,
            policy.resources?.unixSockets ?? [],
        ) ||
        !isDeepStrictEqual(
            report.resources.tcpPublications,
            policy.resources?.tcpPublications ?? [],
        ) ||
        !isDeepStrictEqual(report.docker, policy.docker)
    )
        throw failure(
            "effective resource grants differ from the submitted policy",
        );
}

export function readSandboxAdmission(
    stream: Readable,
): Promise<SandboxAdmission> {
    return new Promise((resolve, reject) => {
        const chunks: Buffer[] = [];
        let length = 0;
        let finished = false;
        const fail = (error: unknown) => {
            if (finished) return;
            finished = true;
            reject(
                error instanceof SandboxExecutionError
                    ? error
                    : failure("channel failed", error),
            );
            stream.destroy();
        };
        stream.on("data", (chunk: Buffer | string) => {
            if (finished) return;
            const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
            length += bytes.length;
            if (length > MAX_ADMISSION_BYTES) {
                fail(failure("report exceeds the 1 MiB limit"));
                return;
            }
            chunks.push(bytes);
        });
        stream.once("error", fail);
        stream.once("close", () => {
            if (!stream.readableEnded)
                fail(failure("channel closed before EOF"));
        });
        stream.once("end", () => {
            if (finished) return;
            try {
                const raw = Buffer.concat(chunks);
                const bytes = raw.at(-1) === 10 ? raw.subarray(0, -1) : raw;
                const report = parseSandboxAdmissionReport(
                    JSON.parse(bytes.toString("utf8")),
                );
                finished = true;
                resolve({
                    report,
                    sha256: createHash("sha256").update(bytes).digest("hex"),
                });
            } catch (error) {
                fail(failure("report is missing or invalid", error));
            }
        });
    });
}
